name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: choosegoose:${{ github.ref_name }}-${{ github.sha }}

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: make all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/Linux*
