name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: choosegoose:${{ github.ref_name }}-${{ github.sha }}

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: make all

    - name: Upload Linux binaries
      uses: actions/upload-artifact@v4
      with:
        name: linux-binaries-${{ github.ref_name }}
        path: build/Linux*/bin

    - name: Upload RG35XX demos
      uses: actions/upload-artifact@v4
      with:
        name: RG35XX-demos-${{ github.ref_name }}
        path: build/RG35XX/demos

