name: Build

permissions:
  contents: write

on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:

  build-RG35XX:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: choosegoose:${{ github.ref_name }}-${{ github.sha }}

    steps:
    - uses: actions/checkout@v6

    - name: Build the Docker image
      run: make rg35xx

    - name: Prepare artifacts
      id: prepare-artifacts
      run: |
        tar czf Linux-arm-uclibcgnueabi.tar.gz build/Linux-arm-uclibcgnueabi/bin
        tar czf RG35XX.tar.gz build/RG35XX

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: Linux-artifacts
        path: "*.tar.gz"

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Cache dependencies
        uses: actions/cache@v5
        id: cache-deps
        with:
          path: ./vendor
          key: ${{ hashFiles('static-compile-deps.sh') }}

      - name: Compile dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          bash static-compile-deps.sh

      - name: Cache font
        uses: actions/cache@v5
        id: cache-font
        with:
          path: ./build/font
          key: font

      - name: Download font
        run: |
          make font-download

      - name: Compile app
        run: |
          make choosegoose

      - name: Smoke test
        run: bash smoke-test.sh

      - name: Prepare artifacts
        id: prepare-artifacts
        run: |
          platform=$(make echo-platform)
          tarfile="$platform.tar.gz" 
          tar czf "$tarfile" "build/$platform/bin"

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: macos-binaries
          path: "*.tar.gz"

  release:
    needs: [build-RG35XX, build-macos]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts

      - name: Flatten artifacts
        run: |
          mkdir dist
          find artifacts -type f -name "*.tar.gz" -exec cp {} dist/ \;

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
