name: Build

permissions:
  contents: write

on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_TAG: choosegoose:latest

jobs:
  build-crosscomp-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: bestie/libnjkafka/.github/actions/docker-gha-cache/build@main
      with:
        tag: ${{ env.DOCKER_TAG }}

  build-RG35XX:
    runs-on: ubuntu-latest
    needs: ["build-crosscomp-image"]

    steps:
    - uses: actions/checkout@v6

    - uses: bestie/libnjkafka/.github/actions/docker-gha-cache/restore@main
      with:
        tag: ${{ env.DOCKER_TAG }}

    - name: Compile binary and demos
      run: |
        docker run --rm \
          --volume "$(pwd)/build:/root/choosegoose/build" \
          ${{ env.DOCKER_TAG }} \
          bash -c "source cross_compilation_env.sh && make choosegoose rg-demos"

    - name: Prepare artifacts
      id: prepare-artifacts
      run: |
        tar czf Linux-arm-uclibcgnueabi.tar.gz build/Linux-arm-uclibcgnueabi/bin
        tar czf RG35XX.tar.gz build/RG35XX

    - name: Upload RG35XX artifacts
      uses: actions/upload-artifact@v6
      with:
        name: RG35XX
        path: RG35XX.tar.gz

    - name: Upload binary
      uses: actions/upload-artifact@v6
      with:
        name: Linux-arm-uclibcgnueabi
        path: Linux-arm-uclibcgnueabi.tar.gz

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Cache dependencies
        uses: actions/cache@v5
        id: cache-deps
        with:
          path: ./vendor
          key: ${{ hashFiles('static-compile-deps.sh') }}

      - name: Compile dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          bash static-compile-deps.sh

      - name: Cache font
        uses: actions/cache@v5
        id: cache-font
        with:
          path: ./build/font
          key: font

      - name: Download font
        run: |
          make font-download

      - name: Compile app
        run: |
          make choosegoose

      - name: Smoke test
        run: bash smoke-test.sh

      - name: Prepare artifacts
        id: prepare-artifacts
        run: |
          platform=$(make echo-platform)
          tarfile="$platform.tar.gz" 
          tar czf "$tarfile" "build/$platform/bin"

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: macos-binaries
          path: "*.tar.gz"

  release:
    needs: [build-RG35XX, build-macos]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: CHANGELOG.md
          fetch-depth: 1

      - name: Download all artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts

      - name: Flatten artifacts
        run: |
          mkdir dist
          find artifacts -type f -name "*.tar.gz" -exec cp {} dist/ \;

      - name: Get the release notes
        run: |
          cat CHANGELOG.md | sed -n '/## v[0-9]/,/## v[0-9]/p' | sed '$d' > release-notes.md

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
          body_path: release-notes.md
          make_latest: true

