name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: choosegoose:${{ github.ref_name }}-${{ github.sha }}

    steps:
    - uses: actions/checkout@v6

    - name: Build the Docker image
      run: make all

    - name: Upload Linux binaries
      uses: actions/upload-artifact@v6
      with:
        name: linux-binaries-${{ github.ref_name }}
        path: build/Linux*/bin

    - name: Upload RG35XX demos
      uses: actions/upload-artifact@v4
      with:
        name: RG35XX-demos-${{ github.ref_name }}
        path: build/RG35XX/demos

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Cache compiled dependencies
        id: cache-deps
        uses: actions/cache@v5
        with:
          path: ./vendor
          key: ${{ hashFiles('./static-compile-deps.sh') }}

      - name: Compile dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          bash static-compile-deps.sh

      - name: Cache font download
        id: cache-font
        uses: actions/cache@v5
        with:
          path: ./build/font
          key: font

      - name: Download font
        if: steps.cache-font.outputs.cache-hit != 'true'
        run: |
          make font-download

      - name: Build
        run: |
          make goose

      - name: Smoke test
        run: |
          EXECUTABLE="./build/$(uname -s)-$(uname -m)-glibc/bin/choosegoose"

          $EXECUTABLE --help | grep "ChooseGoose silly graphical menu system"
          input="$(echo -e "one\ntwo\nthree\n")"
          timeout=1000
          log=goose.log
          command="$EXECUTABLE --background-image=DEFAULT --user-inactivity-timeout-ms=$timeout --log-file=$log"

          time echo "$input" | $command || true

          cat $log

          # Check the log
          cat $log | head -n1 | grep "HONK HONK"        > /dev/null
          cat $log | grep "SDL starting"                > /dev/null
          cat $log | grep "Font loaded"                 > /dev/null
          cat $log | grep "SDL waiting for event"       > /dev/null
          cat $log | grep "Blitting menu item"          > /dev/null
          cat $log | grep "Inactivity timeout reached"  > /dev/null
          echo "Log has stuff in it 👀👍"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: macos-arm64-binary
          path: build/Darwin*/bin
